// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.20.3
// source: api/proto/plugin/v1/plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Phase int32

const (
	Phase_PHASE_UNSPECIFIED      Phase = 0
	Phase_PHASE_REQUEST_HEADERS  Phase = 1
	Phase_PHASE_REQUEST_BODY     Phase = 2
	Phase_PHASE_RESPONSE_HEADERS Phase = 3
	Phase_PHASE_RESPONSE_BODY    Phase = 4
)

// Enum value maps for Phase.
var (
	Phase_name = map[int32]string{
		0: "PHASE_UNSPECIFIED",
		1: "PHASE_REQUEST_HEADERS",
		2: "PHASE_REQUEST_BODY",
		3: "PHASE_RESPONSE_HEADERS",
		4: "PHASE_RESPONSE_BODY",
	}
	Phase_value = map[string]int32{
		"PHASE_UNSPECIFIED":      0,
		"PHASE_REQUEST_HEADERS":  1,
		"PHASE_REQUEST_BODY":     2,
		"PHASE_RESPONSE_HEADERS": 3,
		"PHASE_RESPONSE_BODY":    4,
	}
)

func (x Phase) Enum() *Phase {
	p := new(Phase)
	*p = x
	return p
}

func (x Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_plugin_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (Phase) Type() protoreflect.EnumType {
	return &file_api_proto_plugin_v1_plugin_proto_enumTypes[0]
}

func (x Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Phase.Descriptor instead.
func (Phase) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

type BodyMode int32

const (
	BodyMode_BODY_MODE_NONE      BodyMode = 0
	BodyMode_BODY_MODE_STREAMING BodyMode = 1
	BodyMode_BODY_MODE_BUFFERED  BodyMode = 2
)

// Enum value maps for BodyMode.
var (
	BodyMode_name = map[int32]string{
		0: "BODY_MODE_NONE",
		1: "BODY_MODE_STREAMING",
		2: "BODY_MODE_BUFFERED",
	}
	BodyMode_value = map[string]int32{
		"BODY_MODE_NONE":      0,
		"BODY_MODE_STREAMING": 1,
		"BODY_MODE_BUFFERED":  2,
	}
)

func (x BodyMode) Enum() *BodyMode {
	p := new(BodyMode)
	*p = x
	return p
}

func (x BodyMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BodyMode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_plugin_v1_plugin_proto_enumTypes[1].Descriptor()
}

func (BodyMode) Type() protoreflect.EnumType {
	return &file_api_proto_plugin_v1_plugin_proto_enumTypes[1]
}

func (x BodyMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BodyMode.Descriptor instead.
func (BodyMode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

type Action int32

const (
	Action_ACTION_CONTINUE Action = 0
	Action_ACTION_HALT     Action = 1
	Action_ACTION_MUTATE   Action = 2
	Action_ACTION_DROP     Action = 3
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ACTION_CONTINUE",
		1: "ACTION_HALT",
		2: "ACTION_MUTATE",
		3: "ACTION_DROP",
	}
	Action_value = map[string]int32{
		"ACTION_CONTINUE": 0,
		"ACTION_HALT":     1,
		"ACTION_MUTATE":   2,
		"ACTION_DROP":     3,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_plugin_v1_plugin_proto_enumTypes[2].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_api_proto_plugin_v1_plugin_proto_enumTypes[2]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

type HandshakeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GatewayVersion string                 `protobuf:"bytes,1,opt,name=gateway_version,json=gatewayVersion,proto3" json:"gateway_version,omitempty"`
	PluginId       string                 `protobuf:"bytes,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	ConfigJson     string                 `protobuf:"bytes,3,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_api_proto_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeRequest) GetGatewayVersion() string {
	if x != nil {
		return x.GatewayVersion
	}
	return ""
}

func (x *HandshakeRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *HandshakeRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_api_proto_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HandshakeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_api_proto_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *DescribeRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

type DescribeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Phase          Phase                  `protobuf:"varint,3,opt,name=phase,proto3,enum=plugin.v1.Phase" json:"phase,omitempty"`
	BodyMode       BodyMode               `protobuf:"varint,4,opt,name=body_mode,json=bodyMode,proto3,enum=plugin.v1.BodyMode" json:"body_mode,omitempty"`
	MaxBufferBytes int64                  `protobuf:"varint,5,opt,name=max_buffer_bytes,json=maxBufferBytes,proto3" json:"max_buffer_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_api_proto_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *DescribeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DescribeResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DescribeResponse) GetPhase() Phase {
	if x != nil {
		return x.Phase
	}
	return Phase_PHASE_UNSPECIFIED
}

func (x *DescribeResponse) GetBodyMode() BodyMode {
	if x != nil {
		return x.BodyMode
	}
	return BodyMode_BODY_MODE_NONE
}

func (x *DescribeResponse) GetMaxBufferBytes() int64 {
	if x != nil {
		return x.MaxBufferBytes
	}
	return 0
}

// Envelope encapsulates request/response context delivered to a plugin.
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RouteId       string                 `protobuf:"bytes,2,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Phase         Phase                  `protobuf:"varint,3,opt,name=phase,proto3,enum=plugin.v1.Phase" json:"phase,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	BodyEof       bool                   `protobuf:"varint,7,opt,name=body_eof,json=bodyEof,proto3" json:"body_eof,omitempty"`
	PeerInfo      *PeerInfo              `protobuf:"bytes,8,opt,name=peer_info,json=peerInfo,proto3" json:"peer_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_api_proto_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *Envelope) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Envelope) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *Envelope) GetPhase() Phase {
	if x != nil {
		return x.Phase
	}
	return Phase_PHASE_UNSPECIFIED
}

func (x *Envelope) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Envelope) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Envelope) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Envelope) GetBodyEof() bool {
	if x != nil {
		return x.BodyEof
	}
	return false
}

func (x *Envelope) GetPeerInfo() *PeerInfo {
	if x != nil {
		return x.PeerInfo
	}
	return nil
}

type PeerInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RemoteIp       string                 `protobuf:"bytes,1,opt,name=remote_ip,json=remoteIp,proto3" json:"remote_ip,omitempty"`
	Protocol       string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ClientIdentity string                 `protobuf:"bytes,3,opt,name=client_identity,json=clientIdentity,proto3" json:"client_identity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_api_proto_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *PeerInfo) GetRemoteIp() string {
	if x != nil {
		return x.RemoteIp
	}
	return ""
}

func (x *PeerInfo) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *PeerInfo) GetClientIdentity() string {
	if x != nil {
		return x.ClientIdentity
	}
	return ""
}

// Decision represents the plugin's verdict and any requested mutations.
type Decision struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Action         Action                 `protobuf:"varint,1,opt,name=action,proto3,enum=plugin.v1.Action" json:"action,omitempty"`
	StatusCode     int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // e.g. 401, 403, 429 when action == ACTION_HALT
	Reason         string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	MutateHeaders  map[string]string      `protobuf:"bytes,4,rep,name=mutate_headers,json=mutateHeaders,proto3" json:"mutate_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MutateBody     []byte                 `protobuf:"bytes,5,opt,name=mutate_body,json=mutateBody,proto3" json:"mutate_body,omitempty"`
	MutateMetadata map[string]string      `protobuf:"bytes,6,rep,name=mutate_metadata,json=mutateMetadata,proto3" json:"mutate_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_api_proto_plugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *Decision) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_CONTINUE
}

func (x *Decision) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Decision) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Decision) GetMutateHeaders() map[string]string {
	if x != nil {
		return x.MutateHeaders
	}
	return nil
}

func (x *Decision) GetMutateBody() []byte {
	if x != nil {
		return x.MutateBody
	}
	return nil
}

func (x *Decision) GetMutateMetadata() map[string]string {
	if x != nil {
		return x.MutateMetadata
	}
	return nil
}

// ChunkEnvelope streams individual body chunks to a streaming plugin.
type ChunkEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	IsLast        bool                   `protobuf:"varint,3,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkEnvelope) Reset() {
	*x = ChunkEnvelope{}
	mi := &file_api_proto_plugin_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkEnvelope) ProtoMessage() {}

func (x *ChunkEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkEnvelope.ProtoReflect.Descriptor instead.
func (*ChunkEnvelope) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *ChunkEnvelope) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ChunkEnvelope) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *ChunkEnvelope) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

// ChunkDecision streams back decisions or transformed chunks.
type ChunkDecision struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Action           Action                 `protobuf:"varint,1,opt,name=action,proto3,enum=plugin.v1.Action" json:"action,omitempty"`
	TransformedChunk []byte                 `protobuf:"bytes,2,opt,name=transformed_chunk,json=transformedChunk,proto3" json:"transformed_chunk,omitempty"`
	ErrorReason      string                 `protobuf:"bytes,3,opt,name=error_reason,json=errorReason,proto3" json:"error_reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChunkDecision) Reset() {
	*x = ChunkDecision{}
	mi := &file_api_proto_plugin_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkDecision) ProtoMessage() {}

func (x *ChunkDecision) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkDecision.ProtoReflect.Descriptor instead.
func (*ChunkDecision) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *ChunkDecision) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_CONTINUE
}

func (x *ChunkDecision) GetTransformedChunk() []byte {
	if x != nil {
		return x.TransformedChunk
	}
	return nil
}

func (x *ChunkDecision) GetErrorReason() string {
	if x != nil {
		return x.ErrorReason
	}
	return ""
}

var File_api_proto_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_api_proto_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	" api/proto/plugin/v1/plugin.proto\x12\tplugin.v1\"y\n" +
	"\x10HandshakeRequest\x12'\n" +
	"\x0fgateway_version\x18\x01 \x01(\tR\x0egatewayVersion\x12\x1b\n" +
	"\tplugin_id\x18\x02 \x01(\tR\bpluginId\x12\x1f\n" +
	"\vconfig_json\x18\x03 \x01(\tR\n" +
	"configJson\"T\n" +
	"\x11HandshakeResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\".\n" +
	"\x0fDescribeRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\"\xc4\x01\n" +
	"\x10DescribeResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12&\n" +
	"\x05phase\x18\x03 \x01(\x0e2\x10.plugin.v1.PhaseR\x05phase\x120\n" +
	"\tbody_mode\x18\x04 \x01(\x0e2\x13.plugin.v1.BodyModeR\bbodyMode\x12(\n" +
	"\x10max_buffer_bytes\x18\x05 \x01(\x03R\x0emaxBufferBytes\"\xc1\x03\n" +
	"\bEnvelope\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\broute_id\x18\x02 \x01(\tR\arouteId\x12&\n" +
	"\x05phase\x18\x03 \x01(\x0e2\x10.plugin.v1.PhaseR\x05phase\x12:\n" +
	"\aheaders\x18\x04 \x03(\v2 .plugin.v1.Envelope.HeadersEntryR\aheaders\x12=\n" +
	"\bmetadata\x18\x05 \x03(\v2!.plugin.v1.Envelope.MetadataEntryR\bmetadata\x12\x12\n" +
	"\x04body\x18\x06 \x01(\fR\x04body\x12\x19\n" +
	"\bbody_eof\x18\a \x01(\bR\abodyEof\x120\n" +
	"\tpeer_info\x18\b \x01(\v2\x13.plugin.v1.PeerInfoR\bpeerInfo\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"l\n" +
	"\bPeerInfo\x12\x1b\n" +
	"\tremote_ip\x18\x01 \x01(\tR\bremoteIp\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12'\n" +
	"\x0fclient_identity\x18\x03 \x01(\tR\x0eclientIdentity\"\xb5\x03\n" +
	"\bDecision\x12)\n" +
	"\x06action\x18\x01 \x01(\x0e2\x11.plugin.v1.ActionR\x06action\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12M\n" +
	"\x0emutate_headers\x18\x04 \x03(\v2&.plugin.v1.Decision.MutateHeadersEntryR\rmutateHeaders\x12\x1f\n" +
	"\vmutate_body\x18\x05 \x01(\fR\n" +
	"mutateBody\x12P\n" +
	"\x0fmutate_metadata\x18\x06 \x03(\v2'.plugin.v1.Decision.MutateMetadataEntryR\x0emutateMetadata\x1a@\n" +
	"\x12MutateHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13MutateMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\rChunkEnvelope\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05chunk\x18\x02 \x01(\fR\x05chunk\x12\x17\n" +
	"\ais_last\x18\x03 \x01(\bR\x06isLast\"\x8a\x01\n" +
	"\rChunkDecision\x12)\n" +
	"\x06action\x18\x01 \x01(\x0e2\x11.plugin.v1.ActionR\x06action\x12+\n" +
	"\x11transformed_chunk\x18\x02 \x01(\fR\x10transformedChunk\x12!\n" +
	"\ferror_reason\x18\x03 \x01(\tR\verrorReason*\x86\x01\n" +
	"\x05Phase\x12\x15\n" +
	"\x11PHASE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PHASE_REQUEST_HEADERS\x10\x01\x12\x16\n" +
	"\x12PHASE_REQUEST_BODY\x10\x02\x12\x1a\n" +
	"\x16PHASE_RESPONSE_HEADERS\x10\x03\x12\x17\n" +
	"\x13PHASE_RESPONSE_BODY\x10\x04*O\n" +
	"\bBodyMode\x12\x12\n" +
	"\x0eBODY_MODE_NONE\x10\x00\x12\x17\n" +
	"\x13BODY_MODE_STREAMING\x10\x01\x12\x16\n" +
	"\x12BODY_MODE_BUFFERED\x10\x02*R\n" +
	"\x06Action\x12\x13\n" +
	"\x0fACTION_CONTINUE\x10\x00\x12\x0f\n" +
	"\vACTION_HALT\x10\x01\x12\x11\n" +
	"\rACTION_MUTATE\x10\x02\x12\x0f\n" +
	"\vACTION_DROP\x10\x032\xce\x02\n" +
	"\rPluginService\x12F\n" +
	"\tHandshake\x12\x1b.plugin.v1.HandshakeRequest\x1a\x1c.plugin.v1.HandshakeResponse\x12C\n" +
	"\bDescribe\x12\x1a.plugin.v1.DescribeRequest\x1a\x1b.plugin.v1.DescribeResponse\x125\n" +
	"\tOnRequest\x12\x13.plugin.v1.Envelope\x1a\x13.plugin.v1.Decision\x126\n" +
	"\n" +
	"OnResponse\x12\x13.plugin.v1.Envelope\x1a\x13.plugin.v1.Decision\x12A\n" +
	"\aOnChunk\x12\x18.plugin.v1.ChunkEnvelope\x1a\x18.plugin.v1.ChunkDecision(\x010\x01B:Z8github.com/phaselume/torana/api/proto/plugin/v1;pluginv1b\x06proto3"

var (
	file_api_proto_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_api_proto_plugin_v1_plugin_proto_rawDescData []byte
)

func file_api_proto_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_api_proto_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_api_proto_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_plugin_v1_plugin_proto_rawDesc), len(file_api_proto_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_api_proto_plugin_v1_plugin_proto_rawDescData
}

var file_api_proto_plugin_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_proto_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_proto_plugin_v1_plugin_proto_goTypes = []any{
	(Phase)(0),                // 0: plugin.v1.Phase
	(BodyMode)(0),             // 1: plugin.v1.BodyMode
	(Action)(0),               // 2: plugin.v1.Action
	(*HandshakeRequest)(nil),  // 3: plugin.v1.HandshakeRequest
	(*HandshakeResponse)(nil), // 4: plugin.v1.HandshakeResponse
	(*DescribeRequest)(nil),   // 5: plugin.v1.DescribeRequest
	(*DescribeResponse)(nil),  // 6: plugin.v1.DescribeResponse
	(*Envelope)(nil),          // 7: plugin.v1.Envelope
	(*PeerInfo)(nil),          // 8: plugin.v1.PeerInfo
	(*Decision)(nil),          // 9: plugin.v1.Decision
	(*ChunkEnvelope)(nil),     // 10: plugin.v1.ChunkEnvelope
	(*ChunkDecision)(nil),     // 11: plugin.v1.ChunkDecision
	nil,                       // 12: plugin.v1.Envelope.HeadersEntry
	nil,                       // 13: plugin.v1.Envelope.MetadataEntry
	nil,                       // 14: plugin.v1.Decision.MutateHeadersEntry
	nil,                       // 15: plugin.v1.Decision.MutateMetadataEntry
}
var file_api_proto_plugin_v1_plugin_proto_depIdxs = []int32{
	0,  // 0: plugin.v1.DescribeResponse.phase:type_name -> plugin.v1.Phase
	1,  // 1: plugin.v1.DescribeResponse.body_mode:type_name -> plugin.v1.BodyMode
	0,  // 2: plugin.v1.Envelope.phase:type_name -> plugin.v1.Phase
	12, // 3: plugin.v1.Envelope.headers:type_name -> plugin.v1.Envelope.HeadersEntry
	13, // 4: plugin.v1.Envelope.metadata:type_name -> plugin.v1.Envelope.MetadataEntry
	8,  // 5: plugin.v1.Envelope.peer_info:type_name -> plugin.v1.PeerInfo
	2,  // 6: plugin.v1.Decision.action:type_name -> plugin.v1.Action
	14, // 7: plugin.v1.Decision.mutate_headers:type_name -> plugin.v1.Decision.MutateHeadersEntry
	15, // 8: plugin.v1.Decision.mutate_metadata:type_name -> plugin.v1.Decision.MutateMetadataEntry
	2,  // 9: plugin.v1.ChunkDecision.action:type_name -> plugin.v1.Action
	3,  // 10: plugin.v1.PluginService.Handshake:input_type -> plugin.v1.HandshakeRequest
	5,  // 11: plugin.v1.PluginService.Describe:input_type -> plugin.v1.DescribeRequest
	7,  // 12: plugin.v1.PluginService.OnRequest:input_type -> plugin.v1.Envelope
	7,  // 13: plugin.v1.PluginService.OnResponse:input_type -> plugin.v1.Envelope
	10, // 14: plugin.v1.PluginService.OnChunk:input_type -> plugin.v1.ChunkEnvelope
	4,  // 15: plugin.v1.PluginService.Handshake:output_type -> plugin.v1.HandshakeResponse
	6,  // 16: plugin.v1.PluginService.Describe:output_type -> plugin.v1.DescribeResponse
	9,  // 17: plugin.v1.PluginService.OnRequest:output_type -> plugin.v1.Decision
	9,  // 18: plugin.v1.PluginService.OnResponse:output_type -> plugin.v1.Decision
	11, // 19: plugin.v1.PluginService.OnChunk:output_type -> plugin.v1.ChunkDecision
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_proto_plugin_v1_plugin_proto_init() }
func file_api_proto_plugin_v1_plugin_proto_init() {
	if File_api_proto_plugin_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_plugin_v1_plugin_proto_rawDesc), len(file_api_proto_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_api_proto_plugin_v1_plugin_proto_depIdxs,
		EnumInfos:         file_api_proto_plugin_v1_plugin_proto_enumTypes,
		MessageInfos:      file_api_proto_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_api_proto_plugin_v1_plugin_proto = out.File
	file_api_proto_plugin_v1_plugin_proto_goTypes = nil
	file_api_proto_plugin_v1_plugin_proto_depIdxs = nil
}
