// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.20.3
// source: api/proto/plugin/v1/plugin.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginService_Handshake_FullMethodName  = "/plugin.v1.PluginService/Handshake"
	PluginService_Describe_FullMethodName   = "/plugin.v1.PluginService/Describe"
	PluginService_OnRequest_FullMethodName  = "/plugin.v1.PluginService/OnRequest"
	PluginService_OnResponse_FullMethodName = "/plugin.v1.PluginService/OnResponse"
	PluginService_OnChunk_FullMethodName    = "/plugin.v1.PluginService/OnChunk"
)

// PluginServiceClient is the client API for PluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PluginService defines the interface for out-of-process filter plugins.
type PluginServiceClient interface {
	// Handshake establishes capability negotiation between data plane and plugin.
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	// Describe returns the plugin's declared lifecycle phase and body inspection mode.
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
	// OnRequest evaluates or transforms request headers/metadata and buffered payload.
	OnRequest(ctx context.Context, in *Envelope, opts ...grpc.CallOption) (*Decision, error)
	// OnResponse evaluates or transforms response headers/metadata and buffered payload.
	OnResponse(ctx context.Context, in *Envelope, opts ...grpc.CallOption) (*Decision, error)
	// OnChunk streams raw request/response chunks through the plugin for real-time inspection.
	OnChunk(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChunkEnvelope, ChunkDecision], error)
}

type pluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginServiceClient(cc grpc.ClientConnInterface) PluginServiceClient {
	return &pluginServiceClient{cc}
}

func (c *pluginServiceClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, PluginService_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeResponse)
	err := c.cc.Invoke(ctx, PluginService_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) OnRequest(ctx context.Context, in *Envelope, opts ...grpc.CallOption) (*Decision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Decision)
	err := c.cc.Invoke(ctx, PluginService_OnRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) OnResponse(ctx context.Context, in *Envelope, opts ...grpc.CallOption) (*Decision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Decision)
	err := c.cc.Invoke(ctx, PluginService_OnResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) OnChunk(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChunkEnvelope, ChunkDecision], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PluginService_ServiceDesc.Streams[0], PluginService_OnChunk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChunkEnvelope, ChunkDecision]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginService_OnChunkClient = grpc.BidiStreamingClient[ChunkEnvelope, ChunkDecision]

// PluginServiceServer is the server API for PluginService service.
// All implementations must embed UnimplementedPluginServiceServer
// for forward compatibility.
//
// PluginService defines the interface for out-of-process filter plugins.
type PluginServiceServer interface {
	// Handshake establishes capability negotiation between data plane and plugin.
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	// Describe returns the plugin's declared lifecycle phase and body inspection mode.
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
	// OnRequest evaluates or transforms request headers/metadata and buffered payload.
	OnRequest(context.Context, *Envelope) (*Decision, error)
	// OnResponse evaluates or transforms response headers/metadata and buffered payload.
	OnResponse(context.Context, *Envelope) (*Decision, error)
	// OnChunk streams raw request/response chunks through the plugin for real-time inspection.
	OnChunk(grpc.BidiStreamingServer[ChunkEnvelope, ChunkDecision]) error
	mustEmbedUnimplementedPluginServiceServer()
}

// UnimplementedPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServiceServer struct{}

func (UnimplementedPluginServiceServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedPluginServiceServer) Describe(context.Context, *DescribeRequest) (*DescribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedPluginServiceServer) OnRequest(context.Context, *Envelope) (*Decision, error) {
	return nil, status.Error(codes.Unimplemented, "method OnRequest not implemented")
}
func (UnimplementedPluginServiceServer) OnResponse(context.Context, *Envelope) (*Decision, error) {
	return nil, status.Error(codes.Unimplemented, "method OnResponse not implemented")
}
func (UnimplementedPluginServiceServer) OnChunk(grpc.BidiStreamingServer[ChunkEnvelope, ChunkDecision]) error {
	return status.Error(codes.Unimplemented, "method OnChunk not implemented")
}
func (UnimplementedPluginServiceServer) mustEmbedUnimplementedPluginServiceServer() {}
func (UnimplementedPluginServiceServer) testEmbeddedByValue()                       {}

// UnsafePluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServiceServer will
// result in compilation errors.
type UnsafePluginServiceServer interface {
	mustEmbedUnimplementedPluginServiceServer()
}

func RegisterPluginServiceServer(s grpc.ServiceRegistrar, srv PluginServiceServer) {
	// If the following call panics, it indicates UnimplementedPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginService_ServiceDesc, srv)
}

func _PluginService_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_OnRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Envelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).OnRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_OnRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).OnRequest(ctx, req.(*Envelope))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_OnResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Envelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).OnResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_OnResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).OnResponse(ctx, req.(*Envelope))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_OnChunk_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PluginServiceServer).OnChunk(&grpc.GenericServerStream[ChunkEnvelope, ChunkDecision]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginService_OnChunkServer = grpc.BidiStreamingServer[ChunkEnvelope, ChunkDecision]

// PluginService_ServiceDesc is the grpc.ServiceDesc for PluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.v1.PluginService",
	HandlerType: (*PluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _PluginService_Handshake_Handler,
		},
		{
			MethodName: "Describe",
			Handler:    _PluginService_Describe_Handler,
		},
		{
			MethodName: "OnRequest",
			Handler:    _PluginService_OnRequest_Handler,
		},
		{
			MethodName: "OnResponse",
			Handler:    _PluginService_OnResponse_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OnChunk",
			Handler:       _PluginService_OnChunk_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/plugin/v1/plugin.proto",
}
