// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.20.3
// source: api/proto/controlplane/v1/controlplane.proto

package controlplanev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command_CommandType int32

const (
	Command_UNKNOWN Command_CommandType = 0
	Command_DRAIN   Command_CommandType = 1
	Command_RELOAD  Command_CommandType = 2
	Command_PROBE   Command_CommandType = 3
)

// Enum value maps for Command_CommandType.
var (
	Command_CommandType_name = map[int32]string{
		0: "UNKNOWN",
		1: "DRAIN",
		2: "RELOAD",
		3: "PROBE",
	}
	Command_CommandType_value = map[string]int32{
		"UNKNOWN": 0,
		"DRAIN":   1,
		"RELOAD":  2,
		"PROBE":   3,
	}
)

func (x Command_CommandType) Enum() *Command_CommandType {
	p := new(Command_CommandType)
	*p = x
	return p
}

func (x Command_CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command_CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_controlplane_v1_controlplane_proto_enumTypes[0].Descriptor()
}

func (Command_CommandType) Type() protoreflect.EnumType {
	return &file_api_proto_controlplane_v1_controlplane_proto_enumTypes[0]
}

func (x Command_CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command_CommandType.Descriptor instead.
func (Command_CommandType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{21, 0}
}

// EnrollRequest is sent upon gateway startup to authenticate and obtain initial cluster identity.
type EnrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	EnrollToken   string                 `protobuf:"bytes,3,opt,name=enroll_token,json=enrollToken,proto3" json:"enroll_token,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *EnrollRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *EnrollRequest) GetEnrollToken() string {
	if x != nil {
		return x.EnrollToken
	}
	return ""
}

func (x *EnrollRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *EnrollRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// EnrollResponse returns enrollment status and initial credentials.
type EnrollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	EnrolledAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=enrolled_at,json=enrolledAt,proto3" json:"enrolled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *EnrollResponse) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *EnrollResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *EnrollResponse) GetEnrolledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EnrolledAt
	}
	return nil
}

// NodeMessage is streamed from gateway-data to the platform control plane.
type NodeMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	NodeId    string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Namespace string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*NodeMessage_Hello
	//	*NodeMessage_Ack
	//	*NodeMessage_Nack
	//	*NodeMessage_Heartbeat
	//	*NodeMessage_PluginStatus
	//	*NodeMessage_UsageReport
	Payload       isNodeMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMessage) Reset() {
	*x = NodeMessage{}
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMessage) ProtoMessage() {}

func (x *NodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMessage.ProtoReflect.Descriptor instead.
func (*NodeMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{2}
}

func (x *NodeMessage) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeMessage) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NodeMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *NodeMessage) GetPayload() isNodeMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *NodeMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *NodeMessage) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *NodeMessage) GetNack() *Nack {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_Nack); ok {
			return x.Nack
		}
	}
	return nil
}

func (x *NodeMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *NodeMessage) GetPluginStatus() *PluginStatus {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_PluginStatus); ok {
			return x.PluginStatus
		}
	}
	return nil
}

func (x *NodeMessage) GetUsageReport() *UsageReport {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_UsageReport); ok {
			return x.UsageReport
		}
	}
	return nil
}

type isNodeMessage_Payload interface {
	isNodeMessage_Payload()
}

type NodeMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,4,opt,name=hello,proto3,oneof"`
}

type NodeMessage_Ack struct {
	Ack *Ack `protobuf:"bytes,5,opt,name=ack,proto3,oneof"`
}

type NodeMessage_Nack struct {
	Nack *Nack `protobuf:"bytes,6,opt,name=nack,proto3,oneof"`
}

type NodeMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,7,opt,name=heartbeat,proto3,oneof"`
}

type NodeMessage_PluginStatus struct {
	PluginStatus *PluginStatus `protobuf:"bytes,8,opt,name=plugin_status,json=pluginStatus,proto3,oneof"`
}

type NodeMessage_UsageReport struct {
	UsageReport *UsageReport `protobuf:"bytes,9,opt,name=usage_report,json=usageReport,proto3,oneof"`
}

func (*NodeMessage_Hello) isNodeMessage_Payload() {}

func (*NodeMessage_Ack) isNodeMessage_Payload() {}

func (*NodeMessage_Nack) isNodeMessage_Payload() {}

func (*NodeMessage_Heartbeat) isNodeMessage_Payload() {}

func (*NodeMessage_PluginStatus) isNodeMessage_Payload() {}

func (*NodeMessage_UsageReport) isNodeMessage_Payload() {}

// Hello is sent upon stream establishment to declare node capabilities.
type Hello struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Version            string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	SupportedProtocols []string               `protobuf:"bytes,2,rep,name=supported_protocols,json=supportedProtocols,proto3" json:"supported_protocols,omitempty"`
	SupportedPlugins   []string               `protobuf:"bytes,3,rep,name=supported_plugins,json=supportedPlugins,proto3" json:"supported_plugins,omitempty"`
	StartTime          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{3}
}

func (x *Hello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Hello) GetSupportedProtocols() []string {
	if x != nil {
		return x.SupportedProtocols
	}
	return nil
}

func (x *Hello) GetSupportedPlugins() []string {
	if x != nil {
		return x.SupportedPlugins
	}
	return nil
}

func (x *Hello) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

// Ack confirms successful atomic application of a configuration snapshot or delta.
type Ack struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AppliedConfigVersion uint64                 `protobuf:"varint,1,opt,name=applied_config_version,json=appliedConfigVersion,proto3" json:"applied_config_version,omitempty"`
	Signature            string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{4}
}

func (x *Ack) GetAppliedConfigVersion() uint64 {
	if x != nil {
		return x.AppliedConfigVersion
	}
	return 0
}

func (x *Ack) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

// Nack informs the platform that a configuration update was rejected (e.g. invalid signature, compile error).
type Nack struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	RejectedConfigVersion uint64                 `protobuf:"varint,1,opt,name=rejected_config_version,json=rejectedConfigVersion,proto3" json:"rejected_config_version,omitempty"`
	ErrorCode             string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage          string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Nack) Reset() {
	*x = Nack{}
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nack) ProtoMessage() {}

func (x *Nack) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nack.ProtoReflect.Descriptor instead.
func (*Nack) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{5}
}

func (x *Nack) GetRejectedConfigVersion() uint64 {
	if x != nil {
		return x.RejectedConfigVersion
	}
	return 0
}

func (x *Nack) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *Nack) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Heartbeat reports active load and runtime health metrics.
type Heartbeat struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ActiveConnections    int64                  `protobuf:"varint,1,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	ActiveStreams        int64                  `protobuf:"varint,2,opt,name=active_streams,json=activeStreams,proto3" json:"active_streams,omitempty"`
	MemoryAllocatedBytes int64                  `protobuf:"varint,3,opt,name=memory_allocated_bytes,json=memoryAllocatedBytes,proto3" json:"memory_allocated_bytes,omitempty"`
	CpuUsagePermille     int64                  `protobuf:"varint,4,opt,name=cpu_usage_permille,json=cpuUsagePermille,proto3" json:"cpu_usage_permille,omitempty"`
	CurrentConfigVersion uint64                 `protobuf:"varint,5,opt,name=current_config_version,json=currentConfigVersion,proto3" json:"current_config_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{6}
}

func (x *Heartbeat) GetActiveConnections() int64 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *Heartbeat) GetActiveStreams() int64 {
	if x != nil {
		return x.ActiveStreams
	}
	return 0
}

func (x *Heartbeat) GetMemoryAllocatedBytes() int64 {
	if x != nil {
		return x.MemoryAllocatedBytes
	}
	return 0
}

func (x *Heartbeat) GetCpuUsagePermille() int64 {
	if x != nil {
		return x.CpuUsagePermille
	}
	return 0
}

func (x *Heartbeat) GetCurrentConfigVersion() uint64 {
	if x != nil {
		return x.CurrentConfigVersion
	}
	return 0
}

// PluginStatus reports the operational status of an attached plugin.
type PluginStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // e.g. "HEALTHY", "DEGRADED", "FAILED"
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginStatus) Reset() {
	*x = PluginStatus{}
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginStatus) ProtoMessage() {}

func (x *PluginStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginStatus.ProtoReflect.Descriptor instead.
func (*PluginStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{7}
}

func (x *PluginStatus) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PluginStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PluginStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PluginStatus) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

// UsageReport batches non-sensitive telemetry token usage for billing and quotas.
// CUSTOMER PAYLOADS ARE STRICTLY EXCLUDED.
type UsageReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantReports []*TenantUsage         `protobuf:"bytes,1,rep,name=tenant_reports,json=tenantReports,proto3" json:"tenant_reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageReport) Reset() {
	*x = UsageReport{}
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageReport) ProtoMessage() {}

func (x *UsageReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageReport.ProtoReflect.Descriptor instead.
func (*UsageReport) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{8}
}

func (x *UsageReport) GetTenantReports() []*TenantUsage {
	if x != nil {
		return x.TenantReports
	}
	return nil
}

type TenantUsage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TenantId         string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RouteId          string                 `protobuf:"bytes,2,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Model            string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	PromptTokens     int64                  `protobuf:"varint,4,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int64                  `protobuf:"varint,5,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalRequests    int64                  `protobuf:"varint,6,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	DurationMsSum    int64                  `protobuf:"varint,7,opt,name=duration_ms_sum,json=durationMsSum,proto3" json:"duration_ms_sum,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TenantUsage) Reset() {
	*x = TenantUsage{}
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUsage) ProtoMessage() {}

func (x *TenantUsage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUsage.ProtoReflect.Descriptor instead.
func (*TenantUsage) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{9}
}

func (x *TenantUsage) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantUsage) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *TenantUsage) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *TenantUsage) GetPromptTokens() int64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *TenantUsage) GetCompletionTokens() int64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *TenantUsage) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *TenantUsage) GetDurationMsSum() int64 {
	if x != nil {
		return x.DurationMsSum
	}
	return 0
}

// ControlMessage is streamed from platform control plane to gateway-data.
type ControlMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MessageId string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlMessage_Snapshot
	//	*ControlMessage_Delta
	//	*ControlMessage_PluginAssignment
	//	*ControlMessage_Revocation
	//	*ControlMessage_Command
	Payload       isControlMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{10}
}

func (x *ControlMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ControlMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ControlMessage) GetPayload() isControlMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlMessage) GetSnapshot() *Snapshot {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *ControlMessage) GetDelta() *Delta {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Delta); ok {
			return x.Delta
		}
	}
	return nil
}

func (x *ControlMessage) GetPluginAssignment() *PluginAssignment {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_PluginAssignment); ok {
			return x.PluginAssignment
		}
	}
	return nil
}

func (x *ControlMessage) GetRevocation() *Revocation {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Revocation); ok {
			return x.Revocation
		}
	}
	return nil
}

func (x *ControlMessage) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

type isControlMessage_Payload interface {
	isControlMessage_Payload()
}

type ControlMessage_Snapshot struct {
	Snapshot *Snapshot `protobuf:"bytes,3,opt,name=snapshot,proto3,oneof"`
}

type ControlMessage_Delta struct {
	Delta *Delta `protobuf:"bytes,4,opt,name=delta,proto3,oneof"`
}

type ControlMessage_PluginAssignment struct {
	PluginAssignment *PluginAssignment `protobuf:"bytes,5,opt,name=plugin_assignment,json=pluginAssignment,proto3,oneof"`
}

type ControlMessage_Revocation struct {
	Revocation *Revocation `protobuf:"bytes,6,opt,name=revocation,proto3,oneof"`
}

type ControlMessage_Command struct {
	Command *Command `protobuf:"bytes,7,opt,name=command,proto3,oneof"`
}

func (*ControlMessage_Snapshot) isControlMessage_Payload() {}

func (*ControlMessage_Delta) isControlMessage_Payload() {}

func (*ControlMessage_PluginAssignment) isControlMessage_Payload() {}

func (*ControlMessage_Revocation) isControlMessage_Payload() {}

func (*ControlMessage_Command) isControlMessage_Payload() {}

// Snapshot contains a complete, self-contained configuration snapshot.
type Snapshot struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConfigVersion     uint64                 `protobuf:"varint,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	Ed25519Signature  []byte                 `protobuf:"bytes,2,opt,name=ed25519_signature,json=ed25519Signature,proto3" json:"ed25519_signature,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Routes            []*Route               `protobuf:"bytes,4,rep,name=routes,proto3" json:"routes,omitempty"`
	Policies          []*Policy              `protobuf:"bytes,5,rep,name=policies,proto3" json:"policies,omitempty"`
	AuthnProviders    []*AuthnProvider       `protobuf:"bytes,6,rep,name=authn_providers,json=authnProviders,proto3" json:"authn_providers,omitempty"`
	TokenBudgets      []*TokenBudget         `protobuf:"bytes,7,rep,name=token_budgets,json=tokenBudgets,proto3" json:"token_budgets,omitempty"`
	PluginAssignments []*PluginAssignment    `protobuf:"bytes,8,rep,name=plugin_assignments,json=pluginAssignments,proto3" json:"plugin_assignments,omitempty"`
	Upstreams         []*Upstream            `protobuf:"bytes,9,rep,name=upstreams,proto3" json:"upstreams,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{11}
}

func (x *Snapshot) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *Snapshot) GetEd25519Signature() []byte {
	if x != nil {
		return x.Ed25519Signature
	}
	return nil
}

func (x *Snapshot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Snapshot) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *Snapshot) GetPolicies() []*Policy {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *Snapshot) GetAuthnProviders() []*AuthnProvider {
	if x != nil {
		return x.AuthnProviders
	}
	return nil
}

func (x *Snapshot) GetTokenBudgets() []*TokenBudget {
	if x != nil {
		return x.TokenBudgets
	}
	return nil
}

func (x *Snapshot) GetPluginAssignments() []*PluginAssignment {
	if x != nil {
		return x.PluginAssignments
	}
	return nil
}

func (x *Snapshot) GetUpstreams() []*Upstream {
	if x != nil {
		return x.Upstreams
	}
	return nil
}

// Delta contains incremental configuration changes applied on top of a known base version.
type Delta struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	BaseConfigVersion       uint64                 `protobuf:"varint,1,opt,name=base_config_version,json=baseConfigVersion,proto3" json:"base_config_version,omitempty"`
	TargetConfigVersion     uint64                 `protobuf:"varint,2,opt,name=target_config_version,json=targetConfigVersion,proto3" json:"target_config_version,omitempty"`
	Ed25519Signature        []byte                 `protobuf:"bytes,3,opt,name=ed25519_signature,json=ed25519Signature,proto3" json:"ed25519_signature,omitempty"`
	AddedOrUpdatedRoutes    []*Route               `protobuf:"bytes,4,rep,name=added_or_updated_routes,json=addedOrUpdatedRoutes,proto3" json:"added_or_updated_routes,omitempty"`
	DeletedRouteIds         []string               `protobuf:"bytes,5,rep,name=deleted_route_ids,json=deletedRouteIds,proto3" json:"deleted_route_ids,omitempty"`
	AddedOrUpdatedPolicies  []*Policy              `protobuf:"bytes,6,rep,name=added_or_updated_policies,json=addedOrUpdatedPolicies,proto3" json:"added_or_updated_policies,omitempty"`
	DeletedPolicyIds        []string               `protobuf:"bytes,7,rep,name=deleted_policy_ids,json=deletedPolicyIds,proto3" json:"deleted_policy_ids,omitempty"`
	AddedOrUpdatedUpstreams []*Upstream            `protobuf:"bytes,8,rep,name=added_or_updated_upstreams,json=addedOrUpdatedUpstreams,proto3" json:"added_or_updated_upstreams,omitempty"`
	DeletedUpstreamIds      []string               `protobuf:"bytes,9,rep,name=deleted_upstream_ids,json=deletedUpstreamIds,proto3" json:"deleted_upstream_ids,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Delta) Reset() {
	*x = Delta{}
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delta) ProtoMessage() {}

func (x *Delta) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delta.ProtoReflect.Descriptor instead.
func (*Delta) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{12}
}

func (x *Delta) GetBaseConfigVersion() uint64 {
	if x != nil {
		return x.BaseConfigVersion
	}
	return 0
}

func (x *Delta) GetTargetConfigVersion() uint64 {
	if x != nil {
		return x.TargetConfigVersion
	}
	return 0
}

func (x *Delta) GetEd25519Signature() []byte {
	if x != nil {
		return x.Ed25519Signature
	}
	return nil
}

func (x *Delta) GetAddedOrUpdatedRoutes() []*Route {
	if x != nil {
		return x.AddedOrUpdatedRoutes
	}
	return nil
}

func (x *Delta) GetDeletedRouteIds() []string {
	if x != nil {
		return x.DeletedRouteIds
	}
	return nil
}

func (x *Delta) GetAddedOrUpdatedPolicies() []*Policy {
	if x != nil {
		return x.AddedOrUpdatedPolicies
	}
	return nil
}

func (x *Delta) GetDeletedPolicyIds() []string {
	if x != nil {
		return x.DeletedPolicyIds
	}
	return nil
}

func (x *Delta) GetAddedOrUpdatedUpstreams() []*Upstream {
	if x != nil {
		return x.AddedOrUpdatedUpstreams
	}
	return nil
}

func (x *Delta) GetDeletedUpstreamIds() []string {
	if x != nil {
		return x.DeletedUpstreamIds
	}
	return nil
}

// Route defines matching rules and upstream targets.
type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	PathPrefix    bool                   `protobuf:"varint,3,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UpstreamId    string                 `protobuf:"bytes,6,opt,name=upstream_id,json=upstreamId,proto3" json:"upstream_id,omitempty"`
	PolicyIds     []string               `protobuf:"bytes,7,rep,name=policy_ids,json=policyIds,proto3" json:"policy_ids,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,8,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{13}
}

func (x *Route) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Route) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Route) GetPathPrefix() bool {
	if x != nil {
		return x.PathPrefix
	}
	return false
}

func (x *Route) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Route) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Route) GetUpstreamId() string {
	if x != nil {
		return x.UpstreamId
	}
	return ""
}

func (x *Route) GetPolicyIds() []string {
	if x != nil {
		return x.PolicyIds
	}
	return nil
}

func (x *Route) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// Policy defines a pre-compiled CEL policy or built-in filter rule.
type Policy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                                        // "authn", "authz", "ratelimit", "cel", "schema"
	CelExpression string                 `protobuf:"bytes,4,opt,name=cel_expression,json=celExpression,proto3" json:"cel_expression,omitempty"` // Pre-compiled CEL expression string
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`                                    // "ALLOW", "DENY", "MUTATE", "AUDIT"
	Parameters    map[string]string      `protobuf:"bytes,6,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{14}
}

func (x *Policy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Policy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Policy) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Policy) GetCelExpression() string {
	if x != nil {
		return x.CelExpression
	}
	return ""
}

func (x *Policy) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Policy) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// AuthnProvider configures authentication providers.
type AuthnProvider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "JWT", "API_KEY", "OIDC", "MTLS"
	Issuer        string                 `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
	JwksUrl       string                 `protobuf:"bytes,4,opt,name=jwks_url,json=jwksUrl,proto3" json:"jwks_url,omitempty"`
	SecretRef     *SecretRef             `protobuf:"bytes,5,opt,name=secret_ref,json=secretRef,proto3" json:"secret_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthnProvider) Reset() {
	*x = AuthnProvider{}
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthnProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthnProvider) ProtoMessage() {}

func (x *AuthnProvider) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthnProvider.ProtoReflect.Descriptor instead.
func (*AuthnProvider) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{15}
}

func (x *AuthnProvider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuthnProvider) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AuthnProvider) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *AuthnProvider) GetJwksUrl() string {
	if x != nil {
		return x.JwksUrl
	}
	return ""
}

func (x *AuthnProvider) GetSecretRef() *SecretRef {
	if x != nil {
		return x.SecretRef
	}
	return nil
}

// TokenBudget configures quota enforcement per tenant/model.
type TokenBudget struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	TenantId                  string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ModelId                   string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	MaxPromptTokensPerMin     int64                  `protobuf:"varint,3,opt,name=max_prompt_tokens_per_min,json=maxPromptTokensPerMin,proto3" json:"max_prompt_tokens_per_min,omitempty"`
	MaxCompletionTokensPerMin int64                  `protobuf:"varint,4,opt,name=max_completion_tokens_per_min,json=maxCompletionTokensPerMin,proto3" json:"max_completion_tokens_per_min,omitempty"`
	MaxCostPerDay             float64                `protobuf:"fixed64,5,opt,name=max_cost_per_day,json=maxCostPerDay,proto3" json:"max_cost_per_day,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *TokenBudget) Reset() {
	*x = TokenBudget{}
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenBudget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenBudget) ProtoMessage() {}

func (x *TokenBudget) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenBudget.ProtoReflect.Descriptor instead.
func (*TokenBudget) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{16}
}

func (x *TokenBudget) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TokenBudget) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *TokenBudget) GetMaxPromptTokensPerMin() int64 {
	if x != nil {
		return x.MaxPromptTokensPerMin
	}
	return 0
}

func (x *TokenBudget) GetMaxCompletionTokensPerMin() int64 {
	if x != nil {
		return x.MaxCompletionTokensPerMin
	}
	return 0
}

func (x *TokenBudget) GetMaxCostPerDay() float64 {
	if x != nil {
		return x.MaxCostPerDay
	}
	return 0
}

// PluginAssignment configures dynamic plugin attachment.
type PluginAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                 // gRPC or UDS endpoint
	Phase         string                 `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`                       // "REQUEST_HEADERS", "REQUEST_BODY", "RESPONSE_HEADERS", "RESPONSE_BODY"
	BodyMode      string                 `protobuf:"bytes,4,opt,name=body_mode,json=bodyMode,proto3" json:"body_mode,omitempty"` // "NONE", "STREAMING", "BUFFERED"
	TimeoutMs     int64                  `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,6,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginAssignment) Reset() {
	*x = PluginAssignment{}
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginAssignment) ProtoMessage() {}

func (x *PluginAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginAssignment.ProtoReflect.Descriptor instead.
func (*PluginAssignment) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{17}
}

func (x *PluginAssignment) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PluginAssignment) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *PluginAssignment) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *PluginAssignment) GetBodyMode() string {
	if x != nil {
		return x.BodyMode
	}
	return ""
}

func (x *PluginAssignment) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *PluginAssignment) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

// Upstream defines destination clusters.
type Upstream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"` // "http", "grpc", "postgres", "llm", "mcp"
	Endpoints     []string               `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	MaxConns      int32                  `protobuf:"varint,5,opt,name=max_conns,json=maxConns,proto3" json:"max_conns,omitempty"`
	SecretRefs    []*SecretRef           `protobuf:"bytes,6,rep,name=secret_refs,json=secretRefs,proto3" json:"secret_refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Upstream) Reset() {
	*x = Upstream{}
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Upstream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Upstream) ProtoMessage() {}

func (x *Upstream) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Upstream.ProtoReflect.Descriptor instead.
func (*Upstream) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{18}
}

func (x *Upstream) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Upstream) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Upstream) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *Upstream) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *Upstream) GetMaxConns() int32 {
	if x != nil {
		return x.MaxConns
	}
	return 0
}

func (x *Upstream) GetSecretRefs() []*SecretRef {
	if x != nil {
		return x.SecretRefs
	}
	return nil
}

// SecretRef represents an indirect reference to a secret stored in local secret providers.
type SecretRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"` // "env", "k8s", "vault"
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretRef) Reset() {
	*x = SecretRef{}
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretRef) ProtoMessage() {}

func (x *SecretRef) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretRef.ProtoReflect.Descriptor instead.
func (*SecretRef) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{19}
}

func (x *SecretRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecretRef) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *SecretRef) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// Revocation notifies nodes of revoked credentials or API keys.
type Revocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RevokedTokens []string               `protobuf:"bytes,1,rep,name=revoked_tokens,json=revokedTokens,proto3" json:"revoked_tokens,omitempty"`
	RevokedKeys   []string               `protobuf:"bytes,2,rep,name=revoked_keys,json=revokedKeys,proto3" json:"revoked_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Revocation) Reset() {
	*x = Revocation{}
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Revocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Revocation) ProtoMessage() {}

func (x *Revocation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Revocation.ProtoReflect.Descriptor instead.
func (*Revocation) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{20}
}

func (x *Revocation) GetRevokedTokens() []string {
	if x != nil {
		return x.RevokedTokens
	}
	return nil
}

func (x *Revocation) GetRevokedKeys() []string {
	if x != nil {
		return x.RevokedKeys
	}
	return nil
}

// Command instructs the node to execute operational commands.
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandType   Command_CommandType    `protobuf:"varint,1,opt,name=command_type,json=commandType,proto3,enum=controlplane.v1.Command_CommandType" json:"command_type,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_v1_controlplane_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{21}
}

func (x *Command) GetCommandType() Command_CommandType {
	if x != nil {
		return x.CommandType
	}
	return Command_UNKNOWN
}

func (x *Command) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

var File_api_proto_controlplane_v1_controlplane_proto protoreflect.FileDescriptor

const file_api_proto_controlplane_v1_controlplane_proto_rawDesc = "" +
	"\n" +
	",api/proto/controlplane/v1/controlplane.proto\x12\x0fcontrolplane.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x82\x02\n" +
	"\rEnrollRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12!\n" +
	"\fenroll_token\x18\x03 \x01(\tR\venrollToken\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12B\n" +
	"\x06labels\x18\x05 \x03(\v2*.controlplane.v1.EnrollRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xad\x01\n" +
	"\x0eEnrollResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12;\n" +
	"\venrolled_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"enrolledAt\"\xd5\x03\n" +
	"\vNodeMessage\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12.\n" +
	"\x05hello\x18\x04 \x01(\v2\x16.controlplane.v1.HelloH\x00R\x05hello\x12(\n" +
	"\x03ack\x18\x05 \x01(\v2\x14.controlplane.v1.AckH\x00R\x03ack\x12+\n" +
	"\x04nack\x18\x06 \x01(\v2\x15.controlplane.v1.NackH\x00R\x04nack\x12:\n" +
	"\theartbeat\x18\a \x01(\v2\x1a.controlplane.v1.HeartbeatH\x00R\theartbeat\x12D\n" +
	"\rplugin_status\x18\b \x01(\v2\x1d.controlplane.v1.PluginStatusH\x00R\fpluginStatus\x12A\n" +
	"\fusage_report\x18\t \x01(\v2\x1c.controlplane.v1.UsageReportH\x00R\vusageReportB\t\n" +
	"\apayload\"\xba\x01\n" +
	"\x05Hello\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12/\n" +
	"\x13supported_protocols\x18\x02 \x03(\tR\x12supportedProtocols\x12+\n" +
	"\x11supported_plugins\x18\x03 \x03(\tR\x10supportedPlugins\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\"Y\n" +
	"\x03Ack\x124\n" +
	"\x16applied_config_version\x18\x01 \x01(\x04R\x14appliedConfigVersion\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\"\x82\x01\n" +
	"\x04Nack\x126\n" +
	"\x17rejected_config_version\x18\x01 \x01(\x04R\x15rejectedConfigVersion\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xfb\x01\n" +
	"\tHeartbeat\x12-\n" +
	"\x12active_connections\x18\x01 \x01(\x03R\x11activeConnections\x12%\n" +
	"\x0eactive_streams\x18\x02 \x01(\x03R\ractiveStreams\x124\n" +
	"\x16memory_allocated_bytes\x18\x03 \x01(\x03R\x14memoryAllocatedBytes\x12,\n" +
	"\x12cpu_usage_permille\x18\x04 \x01(\x03R\x10cpuUsagePermille\x124\n" +
	"\x16current_config_version\x18\x05 \x01(\x04R\x14currentConfigVersion\"\x87\x01\n" +
	"\fPluginStatus\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x03R\tlatencyMs\"R\n" +
	"\vUsageReport\x12C\n" +
	"\x0etenant_reports\x18\x01 \x03(\v2\x1c.controlplane.v1.TenantUsageR\rtenantReports\"\xfc\x01\n" +
	"\vTenantUsage\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\broute_id\x18\x02 \x01(\tR\arouteId\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12#\n" +
	"\rprompt_tokens\x18\x04 \x01(\x03R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x05 \x01(\x03R\x10completionTokens\x12%\n" +
	"\x0etotal_requests\x18\x06 \x01(\x03R\rtotalRequests\x12&\n" +
	"\x0fduration_ms_sum\x18\a \x01(\x03R\rdurationMsSum\"\xa4\x03\n" +
	"\x0eControlMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x127\n" +
	"\bsnapshot\x18\x03 \x01(\v2\x19.controlplane.v1.SnapshotH\x00R\bsnapshot\x12.\n" +
	"\x05delta\x18\x04 \x01(\v2\x16.controlplane.v1.DeltaH\x00R\x05delta\x12P\n" +
	"\x11plugin_assignment\x18\x05 \x01(\v2!.controlplane.v1.PluginAssignmentH\x00R\x10pluginAssignment\x12=\n" +
	"\n" +
	"revocation\x18\x06 \x01(\v2\x1b.controlplane.v1.RevocationH\x00R\n" +
	"revocation\x124\n" +
	"\acommand\x18\a \x01(\v2\x18.controlplane.v1.CommandH\x00R\acommandB\t\n" +
	"\apayload\"\x95\x04\n" +
	"\bSnapshot\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\x04R\rconfigVersion\x12+\n" +
	"\x11ed25519_signature\x18\x02 \x01(\fR\x10ed25519Signature\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12.\n" +
	"\x06routes\x18\x04 \x03(\v2\x16.controlplane.v1.RouteR\x06routes\x123\n" +
	"\bpolicies\x18\x05 \x03(\v2\x17.controlplane.v1.PolicyR\bpolicies\x12G\n" +
	"\x0fauthn_providers\x18\x06 \x03(\v2\x1e.controlplane.v1.AuthnProviderR\x0eauthnProviders\x12A\n" +
	"\rtoken_budgets\x18\a \x03(\v2\x1c.controlplane.v1.TokenBudgetR\ftokenBudgets\x12P\n" +
	"\x12plugin_assignments\x18\b \x03(\v2!.controlplane.v1.PluginAssignmentR\x11pluginAssignments\x127\n" +
	"\tupstreams\x18\t \x03(\v2\x19.controlplane.v1.UpstreamR\tupstreams\"\x9f\x04\n" +
	"\x05Delta\x12.\n" +
	"\x13base_config_version\x18\x01 \x01(\x04R\x11baseConfigVersion\x122\n" +
	"\x15target_config_version\x18\x02 \x01(\x04R\x13targetConfigVersion\x12+\n" +
	"\x11ed25519_signature\x18\x03 \x01(\fR\x10ed25519Signature\x12M\n" +
	"\x17added_or_updated_routes\x18\x04 \x03(\v2\x16.controlplane.v1.RouteR\x14addedOrUpdatedRoutes\x12*\n" +
	"\x11deleted_route_ids\x18\x05 \x03(\tR\x0fdeletedRouteIds\x12R\n" +
	"\x19added_or_updated_policies\x18\x06 \x03(\v2\x17.controlplane.v1.PolicyR\x16addedOrUpdatedPolicies\x12,\n" +
	"\x12deleted_policy_ids\x18\a \x03(\tR\x10deletedPolicyIds\x12V\n" +
	"\x1aadded_or_updated_upstreams\x18\b \x03(\v2\x19.controlplane.v1.UpstreamR\x17addedOrUpdatedUpstreams\x120\n" +
	"\x14deleted_upstream_ids\x18\t \x03(\tR\x12deletedUpstreamIds\"\xbe\x02\n" +
	"\x05Route\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1f\n" +
	"\vpath_prefix\x18\x03 \x01(\bR\n" +
	"pathPrefix\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12=\n" +
	"\aheaders\x18\x05 \x03(\v2#.controlplane.v1.Route.HeadersEntryR\aheaders\x12\x1f\n" +
	"\vupstream_id\x18\x06 \x01(\tR\n" +
	"upstreamId\x12\x1d\n" +
	"\n" +
	"policy_ids\x18\a \x03(\tR\tpolicyIds\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\b \x01(\x03R\ttimeoutMs\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x02\n" +
	"\x06Policy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12%\n" +
	"\x0ecel_expression\x18\x04 \x01(\tR\rcelExpression\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12G\n" +
	"\n" +
	"parameters\x18\x06 \x03(\v2'.controlplane.v1.Policy.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa1\x01\n" +
	"\rAuthnProvider\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06issuer\x18\x03 \x01(\tR\x06issuer\x12\x19\n" +
	"\bjwks_url\x18\x04 \x01(\tR\ajwksUrl\x129\n" +
	"\n" +
	"secret_ref\x18\x05 \x01(\v2\x1a.controlplane.v1.SecretRefR\tsecretRef\"\xea\x01\n" +
	"\vTokenBudget\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x128\n" +
	"\x19max_prompt_tokens_per_min\x18\x03 \x01(\x03R\x15maxPromptTokensPerMin\x12@\n" +
	"\x1dmax_completion_tokens_per_min\x18\x04 \x01(\x03R\x19maxCompletionTokensPerMin\x12'\n" +
	"\x10max_cost_per_day\x18\x05 \x01(\x01R\rmaxCostPerDay\"\xbe\x01\n" +
	"\x10PluginAssignment\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x12\x1b\n" +
	"\tbody_mode\x18\x04 \x01(\tR\bbodyMode\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\x03R\ttimeoutMs\x12\x1f\n" +
	"\vconfig_json\x18\x06 \x01(\tR\n" +
	"configJson\"\xcd\x01\n" +
	"\bUpstream\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x1c\n" +
	"\tendpoints\x18\x03 \x03(\tR\tendpoints\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x03R\ttimeoutMs\x12\x1b\n" +
	"\tmax_conns\x18\x05 \x01(\x05R\bmaxConns\x12;\n" +
	"\vsecret_refs\x18\x06 \x03(\v2\x1a.controlplane.v1.SecretRefR\n" +
	"secretRefs\"M\n" +
	"\tSecretRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\"V\n" +
	"\n" +
	"Revocation\x12%\n" +
	"\x0erevoked_tokens\x18\x01 \x03(\tR\rrevokedTokens\x12!\n" +
	"\frevoked_keys\x18\x02 \x03(\tR\vrevokedKeys\"\xaf\x01\n" +
	"\aCommand\x12G\n" +
	"\fcommand_type\x18\x01 \x01(\x0e2$.controlplane.v1.Command.CommandTypeR\vcommandType\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\x03R\ttimeoutMs\"<\n" +
	"\vCommandType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05DRAIN\x10\x01\x12\n" +
	"\n" +
	"\x06RELOAD\x10\x02\x12\t\n" +
	"\x05PROBE\x10\x032\xad\x01\n" +
	"\x13ControlPlaneService\x12I\n" +
	"\x06Enroll\x12\x1e.controlplane.v1.EnrollRequest\x1a\x1f.controlplane.v1.EnrollResponse\x12K\n" +
	"\x06Stream\x12\x1c.controlplane.v1.NodeMessage\x1a\x1f.controlplane.v1.ControlMessage(\x010\x01BFZDgithub.com/phaselume/torana/api/proto/controlplane/v1;controlplanev1b\x06proto3"

var (
	file_api_proto_controlplane_v1_controlplane_proto_rawDescOnce sync.Once
	file_api_proto_controlplane_v1_controlplane_proto_rawDescData []byte
)

func file_api_proto_controlplane_v1_controlplane_proto_rawDescGZIP() []byte {
	file_api_proto_controlplane_v1_controlplane_proto_rawDescOnce.Do(func() {
		file_api_proto_controlplane_v1_controlplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_controlplane_v1_controlplane_proto_rawDesc), len(file_api_proto_controlplane_v1_controlplane_proto_rawDesc)))
	})
	return file_api_proto_controlplane_v1_controlplane_proto_rawDescData
}

var file_api_proto_controlplane_v1_controlplane_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_controlplane_v1_controlplane_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_api_proto_controlplane_v1_controlplane_proto_goTypes = []any{
	(Command_CommandType)(0),      // 0: controlplane.v1.Command.CommandType
	(*EnrollRequest)(nil),         // 1: controlplane.v1.EnrollRequest
	(*EnrollResponse)(nil),        // 2: controlplane.v1.EnrollResponse
	(*NodeMessage)(nil),           // 3: controlplane.v1.NodeMessage
	(*Hello)(nil),                 // 4: controlplane.v1.Hello
	(*Ack)(nil),                   // 5: controlplane.v1.Ack
	(*Nack)(nil),                  // 6: controlplane.v1.Nack
	(*Heartbeat)(nil),             // 7: controlplane.v1.Heartbeat
	(*PluginStatus)(nil),          // 8: controlplane.v1.PluginStatus
	(*UsageReport)(nil),           // 9: controlplane.v1.UsageReport
	(*TenantUsage)(nil),           // 10: controlplane.v1.TenantUsage
	(*ControlMessage)(nil),        // 11: controlplane.v1.ControlMessage
	(*Snapshot)(nil),              // 12: controlplane.v1.Snapshot
	(*Delta)(nil),                 // 13: controlplane.v1.Delta
	(*Route)(nil),                 // 14: controlplane.v1.Route
	(*Policy)(nil),                // 15: controlplane.v1.Policy
	(*AuthnProvider)(nil),         // 16: controlplane.v1.AuthnProvider
	(*TokenBudget)(nil),           // 17: controlplane.v1.TokenBudget
	(*PluginAssignment)(nil),      // 18: controlplane.v1.PluginAssignment
	(*Upstream)(nil),              // 19: controlplane.v1.Upstream
	(*SecretRef)(nil),             // 20: controlplane.v1.SecretRef
	(*Revocation)(nil),            // 21: controlplane.v1.Revocation
	(*Command)(nil),               // 22: controlplane.v1.Command
	nil,                           // 23: controlplane.v1.EnrollRequest.LabelsEntry
	nil,                           // 24: controlplane.v1.Route.HeadersEntry
	nil,                           // 25: controlplane.v1.Policy.ParametersEntry
	(*timestamppb.Timestamp)(nil), // 26: google.protobuf.Timestamp
}
var file_api_proto_controlplane_v1_controlplane_proto_depIdxs = []int32{
	23, // 0: controlplane.v1.EnrollRequest.labels:type_name -> controlplane.v1.EnrollRequest.LabelsEntry
	26, // 1: controlplane.v1.EnrollResponse.enrolled_at:type_name -> google.protobuf.Timestamp
	26, // 2: controlplane.v1.NodeMessage.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 3: controlplane.v1.NodeMessage.hello:type_name -> controlplane.v1.Hello
	5,  // 4: controlplane.v1.NodeMessage.ack:type_name -> controlplane.v1.Ack
	6,  // 5: controlplane.v1.NodeMessage.nack:type_name -> controlplane.v1.Nack
	7,  // 6: controlplane.v1.NodeMessage.heartbeat:type_name -> controlplane.v1.Heartbeat
	8,  // 7: controlplane.v1.NodeMessage.plugin_status:type_name -> controlplane.v1.PluginStatus
	9,  // 8: controlplane.v1.NodeMessage.usage_report:type_name -> controlplane.v1.UsageReport
	26, // 9: controlplane.v1.Hello.start_time:type_name -> google.protobuf.Timestamp
	10, // 10: controlplane.v1.UsageReport.tenant_reports:type_name -> controlplane.v1.TenantUsage
	26, // 11: controlplane.v1.ControlMessage.timestamp:type_name -> google.protobuf.Timestamp
	12, // 12: controlplane.v1.ControlMessage.snapshot:type_name -> controlplane.v1.Snapshot
	13, // 13: controlplane.v1.ControlMessage.delta:type_name -> controlplane.v1.Delta
	18, // 14: controlplane.v1.ControlMessage.plugin_assignment:type_name -> controlplane.v1.PluginAssignment
	21, // 15: controlplane.v1.ControlMessage.revocation:type_name -> controlplane.v1.Revocation
	22, // 16: controlplane.v1.ControlMessage.command:type_name -> controlplane.v1.Command
	26, // 17: controlplane.v1.Snapshot.created_at:type_name -> google.protobuf.Timestamp
	14, // 18: controlplane.v1.Snapshot.routes:type_name -> controlplane.v1.Route
	15, // 19: controlplane.v1.Snapshot.policies:type_name -> controlplane.v1.Policy
	16, // 20: controlplane.v1.Snapshot.authn_providers:type_name -> controlplane.v1.AuthnProvider
	17, // 21: controlplane.v1.Snapshot.token_budgets:type_name -> controlplane.v1.TokenBudget
	18, // 22: controlplane.v1.Snapshot.plugin_assignments:type_name -> controlplane.v1.PluginAssignment
	19, // 23: controlplane.v1.Snapshot.upstreams:type_name -> controlplane.v1.Upstream
	14, // 24: controlplane.v1.Delta.added_or_updated_routes:type_name -> controlplane.v1.Route
	15, // 25: controlplane.v1.Delta.added_or_updated_policies:type_name -> controlplane.v1.Policy
	19, // 26: controlplane.v1.Delta.added_or_updated_upstreams:type_name -> controlplane.v1.Upstream
	24, // 27: controlplane.v1.Route.headers:type_name -> controlplane.v1.Route.HeadersEntry
	25, // 28: controlplane.v1.Policy.parameters:type_name -> controlplane.v1.Policy.ParametersEntry
	20, // 29: controlplane.v1.AuthnProvider.secret_ref:type_name -> controlplane.v1.SecretRef
	20, // 30: controlplane.v1.Upstream.secret_refs:type_name -> controlplane.v1.SecretRef
	0,  // 31: controlplane.v1.Command.command_type:type_name -> controlplane.v1.Command.CommandType
	1,  // 32: controlplane.v1.ControlPlaneService.Enroll:input_type -> controlplane.v1.EnrollRequest
	3,  // 33: controlplane.v1.ControlPlaneService.Stream:input_type -> controlplane.v1.NodeMessage
	2,  // 34: controlplane.v1.ControlPlaneService.Enroll:output_type -> controlplane.v1.EnrollResponse
	11, // 35: controlplane.v1.ControlPlaneService.Stream:output_type -> controlplane.v1.ControlMessage
	34, // [34:36] is the sub-list for method output_type
	32, // [32:34] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_api_proto_controlplane_v1_controlplane_proto_init() }
func file_api_proto_controlplane_v1_controlplane_proto_init() {
	if File_api_proto_controlplane_v1_controlplane_proto != nil {
		return
	}
	file_api_proto_controlplane_v1_controlplane_proto_msgTypes[2].OneofWrappers = []any{
		(*NodeMessage_Hello)(nil),
		(*NodeMessage_Ack)(nil),
		(*NodeMessage_Nack)(nil),
		(*NodeMessage_Heartbeat)(nil),
		(*NodeMessage_PluginStatus)(nil),
		(*NodeMessage_UsageReport)(nil),
	}
	file_api_proto_controlplane_v1_controlplane_proto_msgTypes[10].OneofWrappers = []any{
		(*ControlMessage_Snapshot)(nil),
		(*ControlMessage_Delta)(nil),
		(*ControlMessage_PluginAssignment)(nil),
		(*ControlMessage_Revocation)(nil),
		(*ControlMessage_Command)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_controlplane_v1_controlplane_proto_rawDesc), len(file_api_proto_controlplane_v1_controlplane_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_controlplane_v1_controlplane_proto_goTypes,
		DependencyIndexes: file_api_proto_controlplane_v1_controlplane_proto_depIdxs,
		EnumInfos:         file_api_proto_controlplane_v1_controlplane_proto_enumTypes,
		MessageInfos:      file_api_proto_controlplane_v1_controlplane_proto_msgTypes,
	}.Build()
	File_api_proto_controlplane_v1_controlplane_proto = out.File
	file_api_proto_controlplane_v1_controlplane_proto_goTypes = nil
	file_api_proto_controlplane_v1_controlplane_proto_depIdxs = nil
}
